name: nyxx_commands
version: 5.0.0-dev.3
description: A framework for easily creating slash commands and text commands for Discord using the nyxx library.

homepage: https://github.com/nyxx-discord/nyxx_commands/blob/main/README.md
repository: https://github.com/nyxx-discord/nyxx_commands
issue_tracker: https://github.com/nyxx-discord/nyxx_commands/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: ^5.1.0
  args: ^2.3.0
  dart_style: ^2.2.1
  logging: ^1.0.2
  nyxx: ^4.0.0
  nyxx_interactions: ^4.3.1
  path: ^1.8.1
  fuzzywuzzy: ^0.2.0
  runtime_type: ^1.0.0+1

dev_dependencies:
  build_runner: ^2.1.4
  coverage: ^1.0.3
  lints: ^2.0.0
  mockito: ^5.0.16
  test: ^1.19.0

executables:
  nyxx-compile: compile
